dropbox: add gtk3 as a dependency
Dropbox has stopped vendoring Gtk+3, so the Dropbox GUI failed with:

Traceback (most recent call last):
  File "desktop/dropbox/client/ui/linux/uikit.py", line 268, in setup_gtk_gdk
  File "../linux64_dropbox_virtual_env/lib/python3.8/ctypes/__init__.py", line 451
, in LoadLibrary
  File "../linux64_dropbox_virtual_env/lib/python3.8/ctypes/__init__.py", line 373
, in __init__
OSError: libgtk-3.so.0: cannot open shared object file: No such file or directory

Adding gtk3 as a dependency fixes this.